### ISSUE TITLE
how to make changes?

### ISSUE THREAD

**Issue by ChuanfengZhang** [Rafase282/rafase282.github.io#17]
I already do as the follows:
1.Clone to your desktop.
2.Run npm install.
3.Run gulp to generate the project 
But I don't know how to make changes now.
Could you tell me?

**Comment by Rafase282** [comment]
Well to edit this one is simple, it is just static files, if you are talking about my generator which was linked from here then i would prefer that you ask over that repo's page.

But to answer your question, you make the changes and then you build with gulp.

**Comment by ChuanfengZhang** [comment]
Thank you,I will have a try
